engines:
  shellcheck:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "C"
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

ratings:
   paths:
   - "**.sh"
   - "**.py"
   
