strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

ignore-paths:
  - build
  - htmlcov
  - test

pep8:
    disable:
    options:
        max-line-length: 120

pep257:
    disable:
     - D203
     - D212

pylint:
  disable:
    - line-too-long  # Already checked by pep8
    - relative-import
